# Generated by Django 3.2.10 on 2022-04-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='category/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Производитель')),
                ('Country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='category/', verbose_name='Изображение')),
                ('Articul', models.CharField(max_length=50, verbose_name='Артикул')),
                ('SizeXS', models.BooleanField(default=False, verbose_name='XS')),
                ('SizeS', models.BooleanField(default=False, verbose_name='S')),
                ('SizeM', models.BooleanField(default=False, verbose_name='M')),
                ('SizeL', models.BooleanField(default=False, verbose_name='L')),
                ('SizeXL', models.BooleanField(default=False, verbose_name='XL')),
                ('SizeXXL', models.BooleanField(default=False, verbose_name='XXL')),
                ('UsedCondition', models.CharField(max_length=50, verbose_name='Состояние')),
                ('About', models.TextField(blank=True, verbose_name='Описание')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
                ('Manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
