# Generated by Django 3.2.10 on 2022-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Type', models.CharField(choices=[('Скидка', 'Скидка'), ('Хит', 'Хит'), ('Распродажа', 'Распродажа'), ('Новинка', 'Новинка')], max_length=50, verbose_name='Тип ярлыка')),
            ],
            options={
                'verbose_name': 'Ярлыки',
                'verbose_name_plural': 'Ярлыки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(to='web.Tag'),
        ),
    ]
