# Generated by Django 3.2.10 on 2022-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220417_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размеры',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeXL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeXS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SizeXXL',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='Type',
        ),
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(to='web.Tag', verbose_name='Ярлыки'),
        ),
        migrations.AddField(
            model_name='product',
            name='Sizes',
            field=models.ManyToManyField(to='web.Size', verbose_name='Размеры в наличии'),
        ),
    ]
