# Generated by Django 3.2.10 on 2022-04-17 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220417_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sizes',
            field=models.ManyToManyField(blank=True, to='web.Size', verbose_name='Размеры в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='web.Tag', verbose_name='Ярлыки'),
        ),
    ]
