# Generated by Django 3.2.10 on 2022-04-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220418_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_images',
        ),
        migrations.AddField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(to='web.ProductImage', verbose_name='Изображения товара'),
        ),
    ]
