# Generated by Django 3.2.10 on 2022-04-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220419_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], default='Нет в наличии', max_length=50, verbose_name='Наличие'),
        ),
    ]
