# Generated by Django 3.2.10 on 2022-04-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('product_id', models.CharField(max_length=120)),
                ('product_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Корзина (system)',
                'verbose_name_plural': 'Корзина (system)',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ManyToManyField(blank=True, to='web.ProductImage', verbose_name='Изображения товара'),
        ),
    ]
