# Generated by Django 3.2.10 on 2022-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_category_show_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Index_block',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Не отображать', max_length=50, verbose_name='Блок на главной'),
        ),
    ]
