# Generated by Django 3.2.10 on 2022-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_tag_index_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Index_block',
            new_name='Visible_status',
        ),
    ]
