# Generated by Django 3.2.10 on 2022-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20220529_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
