# Generated by Django 3.2.10 on 2022-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_recommendations_product_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_status',
            field=models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено')], default='Не оплачено', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='Payment_type',
            field=models.CharField(choices=[('При получении', 'При получении'), ('Онлайн', 'Онлайн')], default=0, max_length=50, verbose_name='Тип оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.IntegerField(default=0, verbose_name='Итоговая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Products',
            field=models.TextField(default=0, verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
